name: php-codesniffer

on: [push, pull_request]

jobs:
  check-syntax:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: php-codesniffer         
      uses: pipeline-components/php-codesniffer@v0.12.3

#Ajudar a identificar e corrigir problemas de formatação, estilo e padrões no código PHP, o que é importante para manter um código legível e manutenível.
