on: [push, pull_request]
name: components security
jobs:
    roave_bc_check:
        name: components security
        runs-on: ubuntu-latest
        steps:
              - name: aozora0000/local-php-security-checker
                uses: aozora0000/local-php-security-checker-action@v1
                with:
                    lockFile: './projeto/composer.lock'

        
     #         - name: pipeline-components-php-security-checker
      #          uses: pipeline-components/php-security-checker@v0.10.4
       #         with:
        #            lockFile: './projeto'
            
            
